name: MobSF Scan

on:
  push:
    branches:
      - main
    paths:
      - '**/*.apk'  # Trigger only for APK files

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MobSF Scanner
        uses: rishabhkumar/mobsf-action@v1
        with:
          api_key: ${{ secrets.MOBSF_API_KEY }}  # Your MobSF API Key (set this in GitHub Secrets)
          apk_file: './sample.apk'    # Adjust the file path as needed
          mobsf_url: 'http://12.12.12.37:8000'  # Your MobSF URL (if it's hosted locally or in a Docker container)
