name: MobSF APK Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run MobSF Analysis
        uses: fundacaocerti/mobsf-action@v1.7.2
        env:
          INPUT_FILE_NAME: sample.apk
          SCAN_TYPE: apk
          OUTPUT_FILE_NAME: mobsf-report
