name: Security Scans
on:
  push:
    branches:
      - main
jobs:
  Security:
    name: Security Scans
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: SonarQube Source Code Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Dependencies Scan
        run: snyk test --all-projects
        continue-on-error: false

      - name: Monitor Snyk SCA Scan
        run: snyk monitor --all-projects
        continue-on-error: false

      #- name: ZAP Dynamic Analysis Scan
      #  uses: zaproxy/action-full-scan@v0.12.0
       # with:
        #  target: 'http://www.itsecgames.com/'
       #   rules_file_name: '.github/workflows/rules.zap'
    
