name: Security Scans
on:
  push:
    branches:
      - main
jobs:
  Security:
    name: Security Scans
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: SonarQube Source Code Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      #- name: SonarQube Quality Gate check
       # id: sonarqube-quality-gate-check
      #  uses: sonarsource/sonarqube-quality-gate-action@master
       # timeout-minutes: 5
       # env:
       #  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      #- name: Run Snyk Dependencies Scan
      #  run: snyk test --all-projects --json > snyk_report.json
       # continue-on-error: true
       
      - name: Run Snyk Dependencies Scan
        id: snyk-scan
        run: |
          snyk test --all-projects --json > snyk_report.json || true
        shell: bash

      - name: Debug Snyk JSON Output
        run: |
          echo "Printing snyk_report.json:"
          cat snyk_report.json
          echo "Formatted output using jq:"
          jq '.' snyk_report.json
        shell: bash

      - name: Monitor Snyk SCA Scan
        run: snyk monitor --all-projects
        continue-on-error: true

     # - name: Check for Medium or Higher Severity Issues
      #  id: snyk-check
      #  run: |
      #    issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "medium" or .severity == "high" or .severity == "critical")] | length' snyk_report.json)
      #    if [ "$issues" -gt 0 ]; then
      #      echo "Found $issues medium or higher severity issues."
      #      exit 1
      #    else
      #      echo "No medium or higher severity issues found."
      #    fi
      #  shell: bash

      - name: Check for Medium, High, and Critical Severity Issues
        id: snyk-check
        run: |
          medium_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "medium")] | length' snyk_report.json)
          high_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "high")] | length' snyk_report.json)
          critical_issues=$(jq '[.[] | select(.vulnerabilities != null) | .vulnerabilities[] | select(.severity == "critical")] | length' snyk_report.json)

          echo "Medium issues: $medium_issues"
          echo "High issues: $high_issues"
          echo "Critical issues: $critical_issues"

          if [ "$critical_issues" -gt 0 ]; then
            echo "Job failed: Found $critical_issues critical severity issues."
            exit 1
          else
            echo "No critical severity issues found."
            echo "Medium issues: $medium_issues"
            echo "High issues: $high_issues"
            echo "Job passed despite $((medium_issues + high_issues)) medium and high severity issues."
          fi
        shell: bash



      #- name: ZAP Dynamic Analysis Scan
      #  uses: zaproxy/action-full-scan@v0.12.0
       # with:
         # target: 'https://bwapp.hakhub.net/'
          #rules_file_name: '.github/workflows/rules.zap'


          
    
